/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package MailClient;

import MailClient.Controller.MainController;
import MailClient.Model.MailManager;
import MailClient.Model.ReceiveProtocol;

public class App {

    public static void main(String[] args)
    throws IllegalArgumentException {
        ReceiveProtocol receiveProtocol;
        if (args[4].equals("POP3")) {
            receiveProtocol = ReceiveProtocol.POP3;
        } else if (args[4].equals("IMAP")) {
            receiveProtocol = ReceiveProtocol.IMAP;
        } else {
            throw new IllegalArgumentException("incorrect receive protocol");
        }
        MainController mc = new MainController(args[0], args[1], args[2], args[3], receiveProtocol);
    }
}
