/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package MailClient;

import View.MainFrame;

public class App {

    public static void main(String[] args) {
        MainFrame mainFrame = new MainFrame();
    }
}
